server:
  port: 8019

management:
  endpoints:
    web:
      exposure:
        include: "info,health,service-registry,features"

---
spring:
  profiles: native
  cloud:
    config:
      server:
        native:
          searchLocations: file:/F:/demo/subdir

server:
  port: 8017

test: peer1

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password@localhost:8761/eureka/,http://user:password@localhost:8762/eureka/,http://user:password@localhost:8763/eureka/

