server:
  port: 8084

spring:
  application:
    name: hystrix-client

management:
  server:
    port: 8010

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password@localhost:8761/eureka/,http://user:password@localhost:8762/eureka/,http://user:password@localhost:8763/eureka/
  instance:
    metadata-map:
      management.port: ${management.server.port:8010}
      cluster: SYSTEM

management.endpoints.web.exposure.include: hystrix.stream

---
spring:
  profiles: peer1

server:
  port: 8011

management:
  server:
    port: 8012