server:
  port: 8761

spring:
  application:
    name: peer0

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password@localhost:8761/eureka/,http://user:password@localhost:8762/eureka/,http://user:password@localhost:8763/eureka/
  server:
    renewalPercentThreshold: 0.49
## eureka.server.enableSelfPreservation=false
---

spring:
  profiles: peer1
  application:
    name: peer1

server:
  port: 8762

---

spring:
  profiles: peer2
  application:
    name: peer2
server:
  port: 8763
