server:
  port: 8015

debug: true

spring:
  application:
    name: spring-retry
  cloud:
    loadbalancer:
      retry:
        enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password@localhost:8761/eureka/,http://user:password@localhost:8762/eureka/,http://user:password@localhost:8763/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "info,health,service-registry"

eureka-client:
  ribbon:
    MaxAutoRetries: 1
    MaxAutoRetriesNextServer: 1
    retryableStatusCodes: 500
---
spring:
  profiles: peer1

server:
  port: 8014

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password@localhost:8761/eureka/,http://user:password@localhost:8762/eureka/,http://user:password@localhost:8763/eureka/

isException: true